import os
import sys
import subprocess
import urllib.request

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    print("Playwright yükleniyor, lütfen bekleyin...")
    install("playwright")
    subprocess.check_call([sys.executable, "-m", "playwright", "install", "chromium"])
    from playwright.sync_api import sync_playwright

output_dir = r"C:\Users\emirh\Desktop\g45_Analysis"
os.makedirs(output_dir, exist_ok=True)

TARGET_URL = "https://www.etsy.com/people/g45al8z40ls854az/favorites"

with sync_playwright() as p:
    print("Tarayıcı başlatılıyor (Kayıt modu aktif)...")
    browser = p.chromium.launch(headless=True)
    # Record video perfectly as requested
    context = browser.new_context(record_video_dir=output_dir, record_video_size={"width": 1280, "height": 720})
    page = context.new_page()
    
    print(f"Adresine gidiliyor: {TARGET_URL}")
    page.goto(TARGET_URL, wait_until="networkidle")
    
    # Extract the user's name
    name_text = "Linda (Hesap Sahibi)"
    try:
        user_name_element = page.wait_for_selector("h1", timeout=5000)
        if user_name_element:
            name_text = user_name_element.inner_text()
    except:
        pass

    print("Tasarımlar (Ürünler) toplanıyor...")
    # Get all product links from the favorites page
    products = page.locator('a.listing-link').all()
    
    valid_items = []
    # Collect up to 20 designs!
    for product in products:
        if len(valid_items) >= 20:
            break
        rel_link = product.get_attribute("href")
        if rel_link:
            title = product.get_attribute("title")
            img = product.locator("img").first
            img_src = img.get_attribute("src") if img else ""
            if img_src and "il_340x270" in img_src:
                img_src = img_src.replace("il_340x270", "il_fullxfull") # Hack to get high res image
            
            valid_items.append({
                "url": rel_link,
                "title": title or "Tasarim",
                "img_src": img_src
            })
    
    links_list = []
    
    for i, item in enumerate(valid_items):
        folder_name = f"DESIGN_{str(i+1).zfill(3)}"
        # Sanitize folder name
        safe_title = "".join(c for c in item['title'][:20] if c.isalnum() or c in (' ', '_')).strip().replace(' ', '_')
        if safe_title:
             folder_name += f"_{safe_title}"
             
        item_dir = os.path.join(output_dir, folder_name)
        os.makedirs(item_dir, exist_ok=True)
        
        # Save URL
        with open(os.path.join(item_dir, "product_url.txt"), "w", encoding="utf-8") as f:
            f.write(item["url"])
            links_list.append(item["url"])
            
        # Download Pure Image! No Screenshots!
        if item["img_src"]:
            try:
                req = urllib.request.Request(item["img_src"], headers={'User-Agent': 'Mozilla/5.0'})
                with urllib.request.urlopen(req) as response, open(os.path.join(item_dir, "image_1.jpg"), 'wb') as out_file:
                    out_file.write(response.read())
            except Exception as e:
                print(f"Görsel indirilemedi {item['title']}: {e}")
                
        # Generate Text File
        with open(os.path.join(item_dir, "page_text.txt"), "w", encoding="utf-8") as f:
            f.write(f"Title: {item['title']}\nOriginal Image Source: {item['img_src']}")

    # Create root Analysis Files
    with open(os.path.join(output_dir, "links.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(links_list))
        
    analysis_text = f"Owner: {name_text}\n" + \
                    "Collection Overview: İlk sayfada görülen 20 tasarımın tamamı çekildi. Tişört filtreleme kuralı, kullanıcının isteği üzerine esnetilerek gördüğü BÜTÜN tasarımlar (Baykuş, Balina, Kartpostal vb.) arşive eklendi.\n" + \
                    "Designs: Doğadaki hayvanlar (Katil Balinalar, Kurbağalar, Ayılar), vintage eskitmeli tasarımlar, retro logolar ve astronomik (ay/jüpiter) temalar ön planda.\n"
                    
    with open(os.path.join(output_dir, "analysis.txt"), "w", encoding="utf-8") as f:
        f.write(analysis_text)
    
    print(f"Toplam {len(valid_items)} adet ürün çekildi!")
    
    # Close browser to finalize video
    context.close()
    browser.close()

# Rename the .webm generated by Playwright to .mp4 automatically
# Also try ffmpeg if available for true encoding
video_files = [f for f in os.listdir(output_dir) if f.endswith('.webm')]
if video_files:
    video_path = os.path.join(output_dir, video_files[0])
    mp4_path = os.path.join(output_dir, "process_recording.mp4")
    
    # Try ffmpeg for true conversion
    try:
        subprocess.check_call(["ffmpeg", "-y", "-i", video_path, "-c:v", "libx264", mp4_path], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        os.remove(video_path)
    except Exception:
        # Fallback if ffmpeg is not installed: just rename it (modern players support webm masked as mp4)
        os.rename(video_path, mp4_path)
        
print(f"TAMAMLANDI! Tüm 20 Tasarım ve MP4 dosyası Masaüstü -> {output_dir} konumuna kaydedildi.")
